name: release

env:
  NODE_VERSION: 16.x

on:
  release:
    types:
    - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install node_modules
      run: yarn
    - name: Publish to MS Market Place
      if: success() && (startsWith( github.ref, 'refs/tags/releases/') || startsWith( github.ref, 'refs/tags/v')) && matrix.os == 'ubuntu-latest'
      run: yarn deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Publish to Open VSX Market Place
      if: success() && (startsWith( github.ref, 'refs/tags/releases/') || startsWith( github.ref, 'refs/tags/v')) && matrix.os == 'ubuntu-latest'
      run: npx ovsx publish --pat $OVSX_PAT
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}